name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hey, @${{ github.actor }} welcome to this repository.We appreciate your contribution to the project and we understand that your time is valuable.We will connect you with the owner shortly.'
        pr-message: 'Hey, @${{ github.actor }} welcome to this repository.🎊 Thank you so much for taking the effort to make my project better! We will review your changes as soon as possible. 🙌 Keep making such awesome contributions!'
